.\"
.\"  Copyright 2015 Young Lee (youngleemails@gmail.com)
.\"
.\"	@(#)younglee.1
.\"
.TH YOUNGLEE 1 "February 13, 2015"
.SH NAME
younglee \- Build in command to check out Young Lee's cv on unix like systems.
.SH SEE ALSO
https://github.com/YoungLeeNENU/younglee
.SH TODO
Refresh thpne cv online.
.SH AUTHOR
Young Lee (youngleemails@gmail.com)
